Repository ScottBrenner/cfn-lint-action, pull requests merged in 2021-04, with the labels that each got.

#36 feat(ci): Create workflows/release.yml
  .github/workflows/release.yml
  package.json
Labels: documentation, enhancement

#33 Version 2.0.0
  .dockerignore
  .eslintignore
  .eslintrc.json
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/main.yml
  .gitignore
  .husky/.gitignore
  .husky/pre-commit
  .prettierignore
  CHANGELOG.md
  Dockerfile
  README.md
  THIRD_PARTY_NOTICE.md
  action.yml
  cfn-lint.json
  dist/index.js
  dist/licenses.txt
  entrypoint.sh
  examples/template.yml
  index.js
  lib/setup.js
  lib/utils/getInput.js
  lib/utils/getInputs.js
  lib/utils/helpers.js
  lib/utils/installCLI.js
  lib/utils/runCommand.js
  package-lock.json
  package.json
  screenshot.png
  tests/getInput.test.js
  tests/helpers.test.js
  tests/runCommand.test.js
  tests/setup.test.js
Labels: documentation, enhancement

#43 Re-Introduction of Problem Matchers
  .github/cfn-lint-pull-request.png
  .github/cfn-lint.json
  .github/workflows/main.yml
  .husky/pre-commit
  CHANGELOG.md
  README.md
  action.yml
  dist/index.js
  index.js
  package.json
Labels: documentation, enhancement, javascript

#47 docs: Fix Typo in 'Contributing' Section
  README.md
Labels: documentation, enhancement

#46 feat(dev): GitHub Codespaces Configuration
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  README.md
  dist/index.js
  dist/licenses.txt
  package-lock.json
Labels: docker, enhancement

#49 docs: Create Contribution Guidelines
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  package-lock.json
Labels: documentation, enhancement
