Repository ScottBrenner/cfn-lint-action, pull requests merged in 2022-11, with the labels that each got.

#233 fix(docs): Use shopt for globbing support
  README.md
Labels: documentation, enhancement

#236 fix: W2531 EOL runtime (nodejs12.x) specified
  .github/workflows/main.yml
  examples/template.yml
Labels: bug, enhancement

#238 Bump cfn-lint version used in workflows/main.yml
  .github/workflows/main.yml
Labels: enhancement, dependencies, github_actions

#239 Changes from 'npm install'
  README.md
  dist/index.js
  dist/licenses.txt
  package-lock.json
Labels: enhancement, help wanted, invalid, dependencies, javascript
